apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stripe-html-cleaner-service.fullname" . }}
  labels:
    {{- include "stripe-html-cleaner-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  progressDeadlineSeconds: {{ .Values.DeadlineSeconds }}  
  selector:
    matchLabels:
      {{- include "stripe-html-cleaner-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stripe-html-cleaner-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stripe-html-cleaner-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- if .Values.dumpCollectorEnable }}
      {{- $profile := "" -}}
      {{- $appname := "" -}}
      {{- range .Values.env }}
        {{- if eq .name "PROFILE" }}
          {{- $profile = .value -}}
        {{- end -}}
        {{- if eq .name "APPNAME" }}
          {{- $appname = .value -}}
        {{- end -}}
      {{- end }}
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /dumps/{{ $profile }}/{{ $appname }}
              chmod -R 777 /dumps/{{ $profile }}/{{ $appname }}
          imagePullPolicy: Always
          env:
            {{- toYaml .Values.env | nindent 10 }}
          volumeMounts:
            - name: dumps
              mountPath: /dumps
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.env | nindent 12 }}          
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: actuator
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: 1
            timeoutSeconds: 2
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: 1
            timeoutSeconds: 2
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          lifecycle:
              preStop:
                exec:
                  command: ["sleep", "5"]
          {{- if or .Values.configmap.enabled .Values.dumpCollectorEnable }}
          volumeMounts:
            {{- if .Values.configmap.enabled }}
            - name: properties
              mountPath: /config
            {{- end }}
            {{- if .Values.dumpCollectorEnable }}
            - name: dumps
              mountPath: /dumps
            {{- end }}
          {{- end }}                                
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.configmap.enabled .Values.dumpCollectorEnable }}
      volumes:
        {{- if .Values.configmap.enabled }}
        - name: properties
          configMap:
            name: stripe-html-cleaner-service
        {{- end }}
        {{- if .Values.dumpCollectorEnable }}
        - name: dumps
          hostPath:
            path: /dumps
        {{- end }}
      {{- end }}  
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
