apiVersion: v1
kind: Service
metadata:
  name: {{ include "stripe-html-cleaner-service.fullname" . }}
  labels:
    {{- include "stripe-html-cleaner-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8081
      targetPort: actuator
      protocol: TCP
      name: actuator
  selector:
    {{- include "stripe-html-cleaner-service.selectorLabels" . | nindent 4 }}
