apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.actuatorPort }}
      targetPort: actuator
      protocol: TCP
      name: actuator
  selector:
    {{- include "application.selectorLabels" . | nindent 4 }}
