{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "screenshot-service.fullname" . }}-pdb
  labels:
    {{- include "screenshot-service.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "screenshot-service.selectorLabels" . | nindent 6 }}
{{- end }}