{{- if eq .Values.serviceMonitor.enabled true }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
  labels:
    {{- include "application.labels" . | nindent 4 }}
  name: {{ include "application.name" . }}
spec:
  endpoints:
  - path: /actuator/prometheus
    port: actuator
  selector:
    matchLabels:
      io.kompose.service: {{ include "application.name" . }}
{{- end }}
