{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}
data:
{{ toYaml .Values.configmap.extraScrapeConfigs | indent 2 }}
{{- end }}