{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "emple-ui.fullname" . }}-pdb
  labels:
    {{- include "emple-ui.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "emple-ui.selectorLabels" . | nindent 6 }}
{{- end }}